### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by Gaivoronsky** [sovaai/sova-asr#1]
Hello, please tell me, on what data was the model trained and what was the volume?

**Comment by sxdxfan** [comment]
Hi @kompotiks! We have two acoustic models, one used for phone calls (8 kHz) and the other for user devices (16 kHz). Both were trained on https://github.com/sovaai/sova-dataset + additional private data from our partners' call centres and telegram voice messages. The total amount of data for each domain was roughly about 1.5k hours. We'll update SOVA Dataset repo with more data shortly. You can also check our habr post (in Russian) to go into more detail: https://habr.com/ru/company/ashmanov_net/blog/523412/
