### ISSUE TITLE
Разделение текста на фразы с указанием времени

### ISSUE THREAD

**Issue by demon-ru** [sovaai/sova-asr#10]
Доброго дня.
В настоящий момент использую "vosk" и установил sova попробовать. Прекрасно работает!
Но для реального (неискушённого) использования при переводе в текст телефонных разговоров не хватает:
1. в json ответа разделения на фразы с указанием времени начала фразы
2. (не критично, но будет большим плюсом): расстановка знаков препинания и начальные большие буквы.

**Comment by sxdxfan** [comment]
Добрый день! С последними обновлениями в результате распознавания выдаётся JSON со всеми распознанными словами, таймстампами их начала и конца, а также уверенностями распознавания. Также подключил пунктуатор (пока работает только на GPU).
