### ISSUE TITLE
Распознавание с микрофона ( real time )

### ISSUE THREAD

**Issue by Arto18** [sovaai/sova-asr#12]
Здравствуйте. В readme написано только про тест на wav файлах и обучение модели. Про рил тайм, увы, нет. В speechRecognition.html есть слова про микрофон и хром. Ввожу "http://localhost:8888/asr/" - 405 Method Not Allowed. Не исключаю, что проблема во мне, надеюсь на понимание.

**Comment by sxdxfan** [comment]
Добрый день! Попробуйте перейти на http://localhost:8888, там будет запись с микрофона
