### ISSUE TITLE
ModuleNotFoundError: No module named 'PuzzleLib.Cuda'

### ISSUE THREAD

**Issue by paladosss** [sovaai/sova-asr#13]
Использую только CPU на Яндекс.Облаке, настроил всё под CPU согласно readme, но в итоге ошибка:
`ModuleNotFoundError: No module named 'PuzzleLib.Cuda'`

[Логи тут - LOGS.txt](https://github.com/sovaai/sova-asr/files/7411769/LOGS.txt)

Конфигурации бэкэнда PuzzleLib (Config.py):
```
class Backend(Enum):
	cuda = 0
	hip = 1
	cpu = 2
	intel = 3
```
В PuzzleLib в файле инициализации PuzzleLib/Backend/gpuarray.py есть метод:
`if Config.backend == Config.Backend.cuda: initCuda()`

Help! 👨‍💻

**Comment by sxdxfan** [comment]
Добрый вечер! Пока не поддержали некоторые операции в PuzzleLib, которые используются для пунктуатора, на CPU, попробуйте пока временно отключить пунктуатор, закомментировав 
https://github.com/sovaai/sova-asr/blob/master/file_handler.py#L7
https://github.com/sovaai/sova-asr/blob/master/file_handler.py#L12
и убрав обработку https://github.com/sovaai/sova-asr/blob/master/file_handler.py#L59

**Comment by paladosss** [comment]
Закомментировал и пересобрал - результат не изменился 👨‍💻

Возможно что-то ещё использует CUDA? 
Или вдруг есть возможность откатиться?

**Comment by sxdxfan** [comment]
Как видно из логов, проблема возникла при импорте пунктуатора, нужно убрать его из file_handler и перезапустить контейнер командой `docker-compose up -d --force-recreate`, пересобирать образ не нужно. Что в логах сейчас?

**Comment by C-Alice** [comment]
Исходя из содержания модулей, в частности speech_recognizer
![изображение](https://user-images.githubusercontent.com/57065333/141113963-86b0e4a8-fb50-4086-be36-a7f856dc979b.png)
![изображение](https://user-images.githubusercontent.com/57065333/141114007-c8ae82dd-8bdb-4826-b19e-ab7ce12183a0.png)

инструкция для config.ini некорректна.

![изображение](https://user-images.githubusercontent.com/57065333/141113707-056ef3c6-3bb3-4e0a-9dfd-a5d979f25f99.png)

Все указывает на значение cpu=1.

**Comment by einvogelhub** [comment]
> Использую только CPU на Яндекс.Облаке, настроил всё под CPU согласно readme, но в итоге ошибка: `ModuleNotFoundError: No module named 'PuzzleLib.Cuda'`
> 
> [Логи тут - LOGS.txt](https://github.com/sovaai/sova-asr/files/7411769/LOGS.txt)
> 
> Конфигурации бэкэнда PuzzleLib (Config.py):
> 
> ```
> class Backend(Enum):
> 	cuda = 0
> 	hip = 1
> 	cpu = 2
> 	intel = 3
> ```
> 
> В PuzzleLib в файле инициализации PuzzleLib/Backend/gpuarray.py есть метод: `if Config.backend == Config.Backend.cuda: initCuda()`
> 
> Help! 👨‍💻

При сборке в контейнере почему - то параметр backend = Backend.gpu в библиотеке PuzzleLib в файле Config.py  

Заходим и меняем на backend = Backend.cpu

Это если вы закомментили пунктуатор и снова появляется ошибка No module named 'PuzzleLib.Cuda
https://github.com/sovaai/sova-asr/blob/master/file_handler.py#L7
https://github.com/sovaai/sova-asr/blob/master/file_handler.py#L12
и убрав обработку https://github.com/sovaai/sova-asr/blob/master/file_handler.py#L59

**Comment by sxdxfan** [comment]
Добрый вечер! Попробуйте перебилдить и запустить контейнер с ветки cpu:
https://github.com/sovaai/sova-asr/tree/cpu

Работоспособность проверена
