### ISSUE TITLE
<class 'PuzzleLib.Modules.Module.ModuleError'>: Unsupported dtype <class 'numpy.float16'>

### ISSUE THREAD

**Issue by einvogelhub** [sovaai/sova-asr#14]
(venv) root@node:~/sova-asr# docker-compose up sova-asr
Creating sova-asr ... done
Attaching to sova-asr
sova-asr          | [2021-12-03 12:38:26 +0000] [1] [INFO] Starting gunicorn 20.0.4
sova-asr          | [2021-12-03 12:38:26 +0000] [1] [INFO] Listening at: http://0.0.0.0:8888 (1)
sova-asr          | [2021-12-03 12:38:26 +0000] [1] [INFO] Using worker: sync
sova-asr          | [2021-12-03 12:38:26 +0000] [9] [INFO] Booting worker with pid: 9
sova-asr          | [PuzzleLib] Using device #0 (x86_64)
sova-asr          | [2021-12-03 12:38:34 +0000] [9] [ERROR] Exception in worker process
sova-asr          | Traceback (most recent call last):
sova-asr          |   File "/sova-asr/PuzzleLib/Containers/Container.py", line 220, in calcMode
sova-asr          |     mod.calcMode(T)
sova-asr          |   File "/sova-asr/PuzzleLib/Modules/Pad1D.py", line 96, in calcMode
sova-asr          |     raise ModuleError("Unsupported dtype %s" % T)
sova-asr          | PuzzleLib.Modules.Module.ModuleError: Unsupported dtype <class 'numpy.float16'>
sova-asr          | 
sova-asr          | During handling of the above exception, another exception occurred:
sova-asr          | 
sova-asr          | Traceback (most recent call last):
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
sova-asr          |     worker.init_process()
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 119, in init_process
sova-asr          |     self.load_wsgi()
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
sova-asr          |     self.wsgi = self.app.wsgi()
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
sova-asr          |     self.callable = self.load()
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
sova-asr          |     return self.load_wsgiapp()
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
sova-asr          |     return util.import_app(self.app_uri)
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 358, in import_app
sova-asr          |     mod = importlib.import_module(module)
sova-asr          |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
sova-asr          |     return _bootstrap._gcd_import(name[level:], package, level)
sova-asr          |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
sova-asr          |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
sova-asr          |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
sova-asr          |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
sova-asr          |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
sova-asr          |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
sova-asr          |   File "/sova-asr/app.py", line 2, in <module>
sova-asr          |     from file_handler import FileHandler
sova-asr          |   File "/sova-asr/file_handler.py", line 11, in <module>
sova-asr          |     speech_recognizer = SpeechRecognizer()
sova-asr          |   File "/sova-asr/speech_recognizer.py", line 34, in __init__
sova-asr          |     self.w2l.calcMode(np.float16)
sova-asr          |   File "/sova-asr/PuzzleLib/Containers/Container.py", line 223, in calcMode
sova-asr          |     self.handleError(mod, e)
sova-asr          |   File "/sova-asr/PuzzleLib/Containers/Container.py", line 240, in handleError
sova-asr          |     raise ContainerError("%s:\nModule (%s) error:\n%s%s" % (self, mod, type(e), msg))
sova-asr          | PuzzleLib.Containers.Container.ContainerError: Container Sequential (name: w2l):
sova-asr          | Module (Module Pad1D (name: 0)) error:
sova-asr          | <class 'PuzzleLib.Modules.Module.ModuleError'>: Unsupported dtype <class 'numpy.float16'>
sova-asr          | [2021-12-03 12:38:34 +0000] [9] [INFO] Worker exiting (pid: 9)
sova-asr          | [2021-12-03 12:38:34 +0000] [1] [INFO] Shutting down: Master
sova-asr          | [2021-12-03 12:38:34 +0000] [1] [INFO] Reason: Worker failed to boot.
sova-asr          | [2021-12-03 12:38:35 +0000] [1] [INFO] Starting gunicorn 20.0.4
sova-asr          | [2021-12-03 12:38:35 +0000] [1] [INFO] Listening at: http://0.0.0.0:8888 (1)
sova-asr          | [2021-12-03 12:38:35 +0000] [1] [INFO] Using worker: sync
sova-asr          | [2021-12-03 12:38:35 +0000] [9] [INFO] Booting worker with pid: 9
sova-asr          | [PuzzleLib] Using device #0 (x86_64)
sova-asr          | [2021-12-03 12:38:42 +0000] [9] [ERROR] Exception in worker process
sova-asr          | Traceback (most recent call last):
sova-asr          |   File "/sova-asr/PuzzleLib/Containers/Container.py", line 220, in calcMode
sova-asr          |     mod.calcMode(T)
sova-asr          |   File "/sova-asr/PuzzleLib/Modules/Pad1D.py", line 96, in calcMode
sova-asr          |     raise ModuleError("Unsupported dtype %s" % T)
sova-asr          | PuzzleLib.Modules.Module.ModuleError: Unsupported dtype <class 'numpy.float16'>
sova-asr          | 
sova-asr          | During handling of the above exception, another exception occurred:
sova-asr          | 
sova-asr          | Traceback (most recent call last):
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
sova-asr          |     worker.init_process()
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 119, in init_process
sova-asr          |     self.load_wsgi()
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
sova-asr          |     self.wsgi = self.app.wsgi()
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
sova-asr          |     self.callable = self.load()
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
sova-asr          |     return self.load_wsgiapp()
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
sova-asr          |     return util.import_app(self.app_uri)
sova-asr          |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 358, in import_app
sova-asr          |     mod = importlib.import_module(module)
sova-asr          |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
sova-asr          |     return _bootstrap._gcd_import(name[level:], package, level)
sova-asr          |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
sova-asr          |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
sova-asr          |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
sova-asr          |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
sova-asr          |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
sova-asr          |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
sova-asr          |   File "/sova-asr/app.py", line 2, in <module>
sova-asr          |     from file_handler import FileHandler
sova-asr          |   File "/sova-asr/file_handler.py", line 11, in <module>
sova-asr          |     speech_recognizer = SpeechRecognizer()
sova-asr          |   File "/sova-asr/speech_recognizer.py", line 34, in __init__
sova-asr          |     self.w2l.calcMode(np.float16)
sova-asr          |   File "/sova-asr/PuzzleLib/Containers/Container.py", line 223, in calcMode
sova-asr          |     self.handleError(mod, e)
sova-asr          |   File "/sova-asr/PuzzleLib/Containers/Container.py", line 240, in handleError
sova-asr          |     raise ContainerError("%s:\nModule (%s) error:\n%s%s" % (self, mod, type(e), msg))
sova-asr          | PuzzleLib.Containers.Container.ContainerError: Container Sequential (name: w2l):
sova-asr          | Module (Module Pad1D (name: 0)) error:
sova-asr          | <class 'PuzzleLib.Modules.Module.ModuleError'>: Unsupported dtype <class 'numpy.float16'>
sova-asr          | [2021-12-03 12:38:42 +0000] [9] [INFO] Worker exiting (pid: 9)
sova-asr          | [2021-12-03 12:38:42 +0000] [1] [INFO] Shutting down: Master
sova-asr          | [2021-12-03 12:38:42 +0000] [1] [INFO] Reason: Worker failed to boot.

Запускал в контенйере на ubuntu18.04 , 20.04 mac Big Sur 11.5.2 нигде не работает на cpu
Help

**Comment by sxdxfan** [comment]
Добрый вечер! Попробуйте перебилдить и запустить контейнер с ветки cpu:
https://github.com/sovaai/sova-asr/tree/cpu
