### ISSUE TITLE
Добавление новых слов в словарь

### ISSUE THREAD

**Issue by Pakonigoosy** [sovaai/sova-asr#17]
Как же все-таки правильно добавлять слова в словарь?
Я просто открыл data/vosk/lexicon.txt, в него в алфавитном порядке добавил слова (как я понял, сначала пишется слово, а потом оно же, только по буквам, а в конце пишется вертикальный слэш). Например, если я хочу добавить слово "уборочка", я пишу `уборочка\tу б о р о ч к а |`
Дальше я перезапускаю сервис. Я делал это по-разному, но реззультат постоянно один - после перезапуска сервер перестает реагировать на запросы
Я также пытался сделать так: `docker-compose run sova-asr`
На это он выдает ошибку `out of device memory while allocating 367248384 bytes`
Дальше очень долгие попытки что-то исправить, но в итоге я возвращаюсь всегда к исходным данным

Вопрос следующий: есть ли хоть какой-то туториал на этот проект?

Вполне возможно, что я по неопытности или по незнанию делаю что-то не совсем так или не в том порядке, поэтому получается такая каша

Мне хотелось бы знать три вещи:
1. Как добавлять слова в словарь
2. Как обучать систему (немного об этом в readme написано, но хотелось бы чуть полнее, если есть)
3. Самое главное - как проверить, что мои изменения применились? То есть, как получить вывод из тренировки и проверить, что слова новые добавились?
Спасибо заранее

**Comment by sxdxfan** [comment]
Добрый день! Помимо lexicon.txt файла для добавления слов нужно модифицировать языковую модель. В качестве языковой модели используется бинарный файл lm.klm, полученный из проприетарного корпуса текстов при помощи утилиты https://kheafield.com/code/kenlm. Вы можете взять за основу любой предобработанный набор текстов, содержащий лишь допустимые символы ("а-яё -" и переносы строк для разделения предложений), и при помощи KenLM скомпилировать языковую модель. Файл лексикона может ограничить возможные слова в ЯМ, но не расширить их.
Код дообучения в репозитории предназначен для обучения акустической модели и его не получится использовать для добавления новых слов.
