### ISSUE TITLE
При попытке обучения модели WER: 100

### ISSUE THREAD

**Issue by MadMaxNice** [sovaai/sova-asr#18]
Добрый день!
При попытке обучения модели, по документации puzzlelib, а также используя файлы из [вопроса ](https://github.com/sovaai/sova-asr/issues/3), WER: 100
Прошло 10 эпох обучения, а WER и CER не меняется
Прошу подсказать, через какое кол-во эпох WER должен начать уменьшаться?
Зачем нужны файлы валидации (проверки)?
И, также, транскрипция корректная? Так и должно быть?
Спасибо!

![image](https://user-images.githubusercontent.com/22424847/174316632-4925d9f6-7b28-432a-8b02-102e6024be36.png)

**Comment by sxdxfan** [comment]
Добрый день!
Количество эпох зависит от объёма данных, иногда и за одну эпоху WER может сильно упасть. Нужно ещё подождать, на ранних эпохах транскрипции выглядят похоже на то, что у вас на скриншоте. Постепенно они начнут становиться похожими на реальные слова.
Вся выборка при любом обучении разбивается на обучающую и валидационную, если вопрос про это. Изменение WER на валидации позволяет оценивать качество обученной сети и понимать, когда стоит остановить обучение.
