### ISSUE TITLE
Модель 

### ISSUE THREAD

**Issue by Gaivoronsky** [sovaai/sova-asr#2]
Здравствуйте, не подскажите на каких мощностях происходило обучение модели и как долго? Есть ли варианты дообучения этой модели?

**Comment by sxdxfan** [comment]
Добрый день! Да, дообучить модель можно, но полный готовый код для этого мы пока не выкладывали никуда, однако вы можете попробовать его реализовать самостоятельно, воспользовавшись нашим туториалом: https://puzzlelib.org/ru/tutorials/Wav2Letter/
Что касается мощностей, мы постепенно их наращивали, сначала обучали модель на конфигурации Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz, 12 ядер, 32 GB RAM, NVIDIA GeForce RTX 2080 Ti, потом перешли на Intel(R) Core(TM) i9-9900X CPU @ 3.50GHz, 20 ядер, 64 GB RAM, 4x NVIDIA GeForce RTX 2080 Ti, это были отличные за свои деньги персональные компьютеры. В итоге перешли на арендуемый Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz, 36 ядер, 128 GB RAM, 4x Tesla V100 SXM2 32GB, дело пошло быстрее. Новые данные поступали порционно, поэтому время сложно оценить, оно будет сильно размазано, но если взять все данные, что мы собрали к моменту обучения выложенных моделей, то где-то за неделю на последней конфигурации можно получить модели текущего качества.
