### ISSUE TITLE
Туториал

### ISSUE THREAD

**Issue by Gaivoronsky** [sovaai/sova-asr#3]
Здравствуйте, в туториале упоминаются файлы с кодой на python, такие как PrepareLibrispeech.py, Config.py, dataLoader.py, Train.py, Decoder.py. Но самих их нет, не подскажите где их можно найти

**Comment by sxdxfan** [comment]
Добрый вечер! Да, туториалы мы ещё пополняем, выложу здесь архивом:
[w2l-train.zip](https://github.com/sovaai/sova-asr/files/5674289/w2l-train.zip)

**Comment by sxdxfan** [comment]
[w2l-train.zip](https://github.com/sovaai/sova-asr/files/5679006/w2l-train.zip)
Прошу прощения, забыл один файлик, вот полный комплект

**Comment by Gaivoronsky** [comment]
Скажите, выдает следующую ошибку при установке PuzzleLib. Пробовал собирать из исходников, всё тоже, что я делаю не так? Версия python 3.6.9

> pip install /content/PuzzleLib-1.0.3 --install-option="--backend=cuda"

> /usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py:234: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Processing ./PuzzleLib-1.0.3
Skipping wheel build for PuzzleLib, due to binaries being disabled for it.
Installing collected packages: PuzzleLib
    Running setup.py install for PuzzleLib ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fqqbiw3i/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fqqbiw3i/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1ggxqese/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/PuzzleLib --backend=cuda Check the logs for full command output.

**Comment by sxdxfan** [comment]
@Dekakhrone призываю тебя :)
