### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by Gaivoronsky** [sovaai/sova-asr#4]
Добрый вечер, в туториале упоминается файл Data/dataLoader.py, и также там отсутствует валидационная часть не могли ли бы вы их предоставить, Благодарю

**Comment by sxdxfan** [comment]
Duplicate of #3 
Добрый день!
В другом issue уже приложил все необходимые файлы

**Comment by Gaivoronsky** [comment]
В том архиве есть только Config.py, Decoder.py, PrepareLibrispeech.py, Train.py, Utils.py. При этом в Train идет импорт Data который отсутствует

**Comment by sxdxfan** [comment]
> В том архиве есть только Config.py, Decoder.py, PrepareLibrispeech.py, Train.py, Utils.py. При этом в Train идет импорт Data который отсутствует

Да, прошу прощения, потерялся файлик, добавил в новый архив в комментарии к #3
