### ISSUE TITLE
Скажите, выдает следующую ошибку при установке PuzzleLib. Пробовал собирать из исходников, всё тоже, что я делаю не так? Версия python 3.6.9

### ISSUE THREAD

**Issue by Gaivoronsky** [sovaai/sova-asr#5]
Скажите, выдает следующую ошибку при установке PuzzleLib. Пробовал собирать из исходников, всё тоже, что я делаю не так? Версия python 3.6.9

> pip install /content/PuzzleLib-1.0.3 --install-option="--backend=cuda"

> /usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py:234: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Processing ./PuzzleLib-1.0.3
Skipping wheel build for PuzzleLib, due to binaries being disabled for it.
Installing collected packages: PuzzleLib
    Running setup.py install for PuzzleLib ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-fqqbiw3i/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-fqqbiw3i/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1ggxqese/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/PuzzleLib --backend=cuda Check the logs for full command output.

_Originally posted by @kompotiks in https://github.com/sovaai/sova-asr/issues/3#issuecomment-743231981_

**Comment by Dekakhrone** [comment]
@kompotiks приветствую! Проведите установку в verbose режиме и скиньте сюда логи, а то пока что сообщение не информативное

`pip install /content/PuzzleLib-1.0.3 --verbose --install-option="--backend=cuda"`

**Comment by sxdxfan** [comment]
Закрыто по неактивности, просьба писать по вопросам, связанным с PuzzleLib в соответствующем репозитории

**Comment by GrigoriyAzatyan** [comment]
root@7d98943128c1:/# pip3 install PuzzleLib==1.0.3a0 --install-option="--backend=cuda" --verbose
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py:245: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 21.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
Collecting PuzzleLib==1.0.3a0
  Using cached PuzzleLib-1.0.3a0.tar.gz (490 kB)
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-tzdwnvnc/PuzzleLib.egg-info
  writing /tmp/pip-pip-egg-info-tzdwnvnc/PuzzleLib.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-tzdwnvnc/PuzzleLib.egg-info/dependency_links.txt
  writing top-level names to /tmp/pip-pip-egg-info-tzdwnvnc/PuzzleLib.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-tzdwnvnc/PuzzleLib.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-tzdwnvnc/PuzzleLib.egg-info/SOURCES.txt'
  writing manifest file '/tmp/pip-pip-egg-info-tzdwnvnc/PuzzleLib.egg-info/SOURCES.txt'
  /usr/lib/python3/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing '1.0.3a' to '1.0.3a0'
    normalized_version,
  Preparing metadata (setup.py) ... done
Skipping wheel build for PuzzleLib, due to binaries being disabled for it.
Installing collected packages: PuzzleLib
    Running command /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-46enya2a/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/PuzzleLib --backend=cuda
    /usr/lib/python3/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing '1.0.3a' to '1.0.3a0'
      normalized_version,
    running install
    backends chosen: ['cuda']
    converters chosen: []

    Checking if all dependencies for Cuda are satisfied ...
    Checking CUDA installation ...
    CUDA V10.2.89 and SDK libraries are found!
    Continuing ...

    Checking NVCC compiler ...
    nvcc compiled test kernel with output:
    Continuing ...

    Checking compiled CUDA kernel ...
    Test kernel answered: finished successfully!
    Continuing ...

    All done, exiting ...

    Building Cuda driver ...
    Compiler invocation: gcc -Wall -Wextra -fPIC -std=gnu99 -O3 -march=native -mtune=native -ffast-math -DNDEBUG -I/usr/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/local/cuda/include --shared -L/usr/lib -L/usr/local/cuda/lib64 -o ../Driver.cpython-36m-x86_64-linux-gnu.so -flto ././Core/AllocVector.gen.c ././Core/Allocator.c ././Core/Array.c ././Core/Buffer.c ././Core/Device.c ././Core/Driver.c ././Core/Module.c ././Core/Stream.c ././TraceMalloc/AllocTree.gen.c ././TraceMalloc/TraceMalloc.gen.c ././Libs/CuRand.c ././Libs/CuBlas.c ././Libs/CuDnn.c ././Libs/CuDnnPool.c ././Libs/CuDnnNorm.c ././Libs/CuDnnMemory.c ././Libs/CuDnnRnn.c ././Libs/CuDnnSpatialTf.c -lpython3.6m -lcuda -lcudart -lnvrtc -lcurand -lcublas -lcudnn
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/setup.py", line 470, in <module>
        main()
      File "/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/setup.py", line 465, in main
        keywords=["puzzlelib", "deep learning", "neural nets"]
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/setup.py", line 119, in run
        self.distribution.package_data = self.installPackages(self.projectPath, self.cachePath, handlers, options)
      File "/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/setup.py", line 148, in installPackages
        packageData.update(handler(pkgSrc, pkgDst, options))
      File "/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/setup.py", line 195, in installGpuPackages
        data.update(self.installGpuPackage("Cuda", checkCudaInstall, buildDriver, cudaDst))
      File "/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/setup.py", line 223, in installGpuPackage
        driver = os.path.abspath(buildDriver())
      File "/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/PuzzleLib/Cuda/Source/Build.py", line 126, in main
      File "/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/PuzzleLib/Cuda/Source/Build.py", line 18, in buildDriver
      File "/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/PuzzleLib/Compiler/Compilers/Compiler.py", line 138, in build
      File "/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/PuzzleLib/Compiler/Compilers/Compiler.py", line 181, in invoke
    PuzzleLib.Compiler.Compilers.Compiler.CompilerError: Compiler invocation failed: gcc -Wall -Wextra -fPIC -std=gnu99 -O3 -march=native -mtune=native -ffast-math -DNDEBUG -I/usr/include/python3.6m -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/local/cuda/include --shared -L/usr/lib -L/usr/local/cuda/lib64 -o ../Driver.cpython-36m-x86_64-linux-gnu.so -flto ././Core/AllocVector.gen.c ././Core/Allocator.c ././Core/Array.c ././Core/Buffer.c ././Core/Device.c ././Core/Driver.c ././Core/Module.c ././Core/Stream.c ././TraceMalloc/AllocTree.gen.c ././TraceMalloc/TraceMalloc.gen.c ././Libs/CuRand.c ././Libs/CuBlas.c ././Libs/CuDnn.c ././Libs/CuDnnPool.c ././Libs/CuDnnNorm.c ././Libs/CuDnnMemory.c ././Libs/CuDnnRnn.c ././Libs/CuDnnSpatialTf.c -lpython3.6m -lcuda -lcudart -lnvrtc -lcurand -lcublas -lcudnn

    In file included from ././Core/AllocVector.gen.h:7:0,
                     from ././Core/AllocVector.gen.c:2:
    ././Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Core/Driver.h:3:0,
                     from ././Core/Allocator.c:5:
    ././Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Core/Driver.h:3:0,
                     from ././Core/Array.c:1:
    ././Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Core/Driver.h:3:0,
                     from ././Core/Buffer.c:1:
    ././Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Core/Driver.h:3:0,
                     from ././Core/Device.c:1:
    ././Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Core/Driver.h:3:0,
                     from ././Core/Driver.c:2:
    ././Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Core/Driver.h:3:0,
                     from ././Core/Module.c:1:
    ././Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Core/Driver.h:3:0,
                     from ././Core/Stream.c:1:
    ././Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Libs/../Core/Driver.h:3:0,
                     from ././Libs/Libs.h:3,
                     from ././Libs/CuRand.c:1:
    ././Libs/../Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Libs/../Core/Driver.h:3:0,
                     from ././Libs/Libs.h:3,
                     from ././Libs/CuBlas.c:1:
    ././Libs/../Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Libs/../Core/Driver.h:3:0,
                     from ././Libs/Libs.h:3,
                     from ././Libs/CuDnn.c:1:
    ././Libs/../Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Libs/../Core/Driver.h:3:0,
                     from ././Libs/Libs.h:3,
                     from ././Libs/CuDnnPool.c:1:
    ././Libs/../Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Libs/../Core/Driver.h:3:0,
                     from ././Libs/Libs.h:3,
                     from ././Libs/CuDnnNorm.c:1:
    ././Libs/../Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Libs/../Core/Driver.h:3:0,
                     from ././Libs/Libs.h:3,
                     from ././Libs/CuDnnMemory.c:1:
    ././Libs/../Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Libs/../Core/Driver.h:3:0,
                     from ././Libs/Libs.h:3,
                     from ././Libs/CuDnnRnn.c:1:
    ././Libs/../Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.
    In file included from ././Libs/../Core/Driver.h:3:0,
                     from ././Libs/Libs.h:3,
                     from ././Libs/CuDnnSpatialTf.c:1:
    ././Libs/../Core/Common.h:37:11: fatal error: cudnn.h: No such file or directory
      #include <cudnn.h>
               ^~~~~~~~~
    compilation terminated.

    Running setup.py install for PuzzleLib ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tlardirt/puzzlelib_fa780652d5824a6d9a63a11f63becf77/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-46enya2a/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/PuzzleLib --backend=cuda Check the logs for full command output.

**Comment by GrigoriyAzatyan** [comment]
У меня такая же проблема (см. выше)
