### ISSUE TITLE
File spectrogram

### ISSUE THREAD

**Issue by LuckyMO285** [sovaai/sova-asr#6]
Здравствуйте!
Не могли бы вы объяснить, почему в спектрограммах аудиофайлов в вашем наборе данных (https://github.com/sovaai/sova-dataset/) есть вырезанные прямоугольные сегменты? 
И почему эта данные выглядят как отраженные относительно оси, проходящей на частоте в 4кГц, но при этом с меньшей интенсивностью?
![image](https://user-images.githubusercontent.com/20071024/102226840-eeda6100-3ef9-11eb-96de-05ec5f9a3122.png)

**Comment by sxdxfan** [comment]
Добрый день! Это очень похоже на спектральную аугментацию, возможно, какая-то часть датасета была предобработана. Много таких файлов встретилось?

**Comment by LuckyMO285** [comment]
Я посмотрел не так много, но такой эффект был во всех присутствующих файлах. 
И такой вопрос: разве аугментация не будет затрагивать всю полосу при ее применении? Т.е. если идет 
применение аугментации "time masking" (на котору. больше всего и похожа аугментация на картинке выше), то она не должна идти по всей вертикали частоты от 0 до 8кГц?
Есть еще один вопрос: в статье (https://habr.com/ru/company/ashmanov_net/blog/523412/) указано, что файлы с телефонными звонками были записаны с частотой 8кГц, однако в вашем датасете они представлены в частоте 16кГц. Не означает ли это, что вы выложили не исходный датасет, а уже измененный по частоте дискретизации?
P.S. я примерно понимаю с чем связана картина отражения на верхней картинке по частоте в 4кГц, но хотелось бы попросить сначала вашего объяснения, что могло ее вызвать.

**Comment by sxdxfan** [comment]
Да, обычно маскируют полосами, по вертикали или горизонтали. Но странно, что такое вообще оказалось в датасете, насколько я помню, мы не применяли аугментаций к выкладываемому датасету. Уточним этот вопрос.
По поводу частоты дискретизации - да, телефонная модель обучалась на аудио в 8 кГц, возможно, был выложен апсемпл, тоже уточним.

**Comment by LuckyMO285** [comment]
По поводу такого поведения с отражением, советую посмотреть в сторону библиотеки pydub и используемых функций из audio_segment.py.
Насколько я заметил, именно при изменении частоты дискретизации с 8кГц до 16кГц и проявляется такой эффект. Буду ожидать обновления по датасету!

**Comment by sxdxfan** [comment]
Очень интересно, спасибо! Посмотрим

Вообще ожидайте ещё пополнения датасета в ближайший месяц, может, ещё и текущий перевыложим в исходной частоте дискретизации.

**Comment by dmzubr** [comment]
Добрый день!

Без новостей по переопубликованию датасета?
@sxdxfan
