### ISSUE TITLE
ERROR: Service 'sova-asr' failed to build

### ISSUE THREAD

**Issue by dimitrievgs** [sovaai/sova-asr#7]
Добрый день, сделал по инструкции, опцию с CUDA не подключал, при вводе команды 

> sudo docker-compose build sova-asr

Пишет:

> Building sova-asr
> Step 1/18 : FROM ubuntu:18.04
> 18.04: Pulling from library/ubuntu
> d519e2592276: Pull complete
> d22d2dfcfa9c: Pull complete
> b3afe92c540b: Pull complete
> Digest: sha256:ea188fdc5be9b25ca048f1e882b33f1bc763fb976a8a4fea446b38ed0efcbeba
> Status: Downloaded newer image for ubuntu:18.04
>  ---> c090eaba6b94
> Step 2/18 : ARG DEBIAN_FRONTEND=noninteractive
>  ---> Running in b6e9aab5a539
> Removing intermediate container b6e9aab5a539
>  ---> d3abc590b3f0
> Step 3/18 : RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
>  ---> Running in e3ce3448b552
> ERROR: Service 'sova-asr' failed to build: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v2.task/moby/e3ce3448b552e7de76807934ea820204a201a1bb829e3b709d80fe6934c9379e/log.json: no such file or directory): exec: "nvidia-container-runtime": executable file not found in $PATH: unknown

**Comment by dimitrievgs** [comment]
После использования команд из секции "(Optional) If you're planning on using CUDA ..."

Выдаёт следующее:

> sudo docker-compose build sova-asr


> Building sova-asr
> Step 1/18 : FROM ubuntu:18.04
>  ---> c090eaba6b94
> Step 2/18 : ARG DEBIAN_FRONTEND=noninteractive
>  ---> Using cache
>  ---> d3abc590b3f0
> Step 3/18 : RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
>  ---> Using cache
>  ---> d7859117deb6
> Step 4/18 : RUN apt-get install -y     vim     libreadline-gplv2-dev     libncursesw5-dev     libssl-dev     libsqlite3-dev     tk-dev     libgdbm-dev     libc6-dev     libbz2-dev     python3-setuptools     libboost-all-dev     build-essential     checkinstall     libc-dev     python3-pkg-resources     python-setuptools-doc     python3-pip     libglib2.0-0     libsm6     libxext6     libxrender-dev     git     ffmpeg     apt-utils
>  ---> Running in 6303e02d6e36
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Package apt-utils is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   apt
> 
> E: Unable to locate package vim
> E: Unable to locate package libreadline-gplv2-dev
> E: Unable to locate package libncursesw5-dev
> E: Unable to locate package libssl-dev
> E: Unable to locate package libsqlite3-dev
> E: Unable to locate package tk-dev
> E: Unable to locate package libgdbm-dev
> E: Unable to locate package libc6-dev
> E: Unable to locate package libbz2-dev
> E: Unable to locate package python3-setuptools
> E: Unable to locate package libboost-all-dev
> E: Unable to locate package build-essential
> E: Unable to locate package checkinstall
> E: Unable to locate package libc-dev
> E: Unable to locate package python3-pkg-resources
> E: Unable to locate package python-setuptools-doc
> E: Unable to locate package python3-pip
> E: Unable to locate package libglib2.0-0
> E: Couldn't find any package by glob 'libglib2.0-0'
> E: Couldn't find any package by regex 'libglib2.0-0'
> E: Unable to locate package libsm6
> E: Unable to locate package libxext6
> E: Unable to locate package libxrender-dev
> E: Unable to locate package git
> E: Unable to locate package ffmpeg
> E: Package 'apt-utils' has no installation candidate
> ERROR: Service 'sova-asr' failed to build: The command '/bin/sh -c apt-get install -y     vim     libreadline-gplv2-dev     libncursesw5-dev     libssl-dev     libsqlite3-dev     tk-dev     libgdbm-dev     libc6-dev     libbz2-dev     python3-setuptools     libboost-all-dev     build-essential     checkinstall     libc-dev     python3-pkg-resources     python-setuptools-doc     python3-pip     libglib2.0-0     libsm6     libxext6     libxrender-dev     git     ffmpeg     apt-utils' returned a non-zero code: 100

**Comment by sxdxfan** [comment]
Добрый день! Файлик /etc/docker/daemon.json меняли? Его нужно изменять только если планируете использовать GPU. Для CPU версии удалите просто этот файлик и перезапустите docker сервис, затем проведите повторный запуск CPU версии

**Comment by dimitrievgs** [comment]
Удалил файл 
> sudo rm /etc/docker/daemon.json

Удалил папку sova-asr, повторно прогнал команды
> sudo systemctl restart docker.service
> git clone --recursive https://github.com/sovaai/sova-asr.git
> cd sova-asr/
> wget http://dataset.sova.ai/SOVA-ASR/Data.tar
> tar -xvf Data.tar

Запустил:
> sudo docker-compose build sova-asr

Результат:
> Building sova-asr
> Step 1/18 : FROM ubuntu:18.04
>  ---> c090eaba6b94
> Step 2/18 : ARG DEBIAN_FRONTEND=noninteractive
>  ---> Using cache
>  ---> d3abc590b3f0
> Step 3/18 : RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
>  ---> Using cache
>  ---> d7859117deb6
> Step 4/18 : RUN apt-get install -y     vim     libreadline-gplv2-dev     libncursesw5-dev     libssl-dev     libsqlite3-dev     tk-dev     libgdbm-dev     libc6-dev     libbz2-dev     python3-setuptools     libboost-all-dev     build-essential     checkinstall     libc-dev     python3-pkg-resources     python-setuptools-doc     python3-pip     libglib2.0-0     libsm6     libxext6     libxrender-dev     git     ffmpeg     apt-utils
>  ---> Running in fbc735566250
> Reading package lists...
> Building dependency tree...
> Reading state information...
> Package apt-utils is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   apt
> 
> E: Unable to locate package vim
> E: Unable to locate package libreadline-gplv2-dev
> E: Unable to locate package libncursesw5-dev
> E: Unable to locate package libssl-dev
> E: Unable to locate package libsqlite3-dev
> E: Unable to locate package tk-dev
> E: Unable to locate package libgdbm-dev
> E: Unable to locate package libc6-dev
> E: Unable to locate package libbz2-dev
> E: Unable to locate package python3-setuptools
> E: Unable to locate package libboost-all-dev
> E: Unable to locate package build-essential
> E: Unable to locate package checkinstall
> E: Unable to locate package libc-dev
> E: Unable to locate package python3-pkg-resources
> E: Unable to locate package python-setuptools-doc
> E: Unable to locate package python3-pip
> E: Unable to locate package libglib2.0-0
> E: Couldn't find any package by glob 'libglib2.0-0'
> E: Couldn't find any package by regex 'libglib2.0-0'
> E: Unable to locate package libsm6
> E: Unable to locate package libxext6
> E: Unable to locate package libxrender-dev
> E: Unable to locate package git
> E: Unable to locate package ffmpeg
> E: Package 'apt-utils' has no installation candidate
> ERROR: Service 'sova-asr' failed to build: The command '/bin/sh -c apt-get install -y     vim     libreadline-gplv2-dev     libncursesw5-dev     libssl-dev     libsqlite3-dev     tk-dev     libgdbm-dev     libc6-dev     libbz2-dev     python3-setuptools     libboost-all-dev     build-essential     checkinstall     libc-dev     python3-pkg-resources     python-setuptools-doc     python3-pip     libglib2.0-0     libsm6     libxext6     libxrender-dev     git     ffmpeg     apt-utils' returned a non-zero code: 100

**Comment by sxdxfan** [comment]
Возможно, проблема в кеше, попробуйте запустить билд с флагом --no-cache.

Вообще на предыдущих шагах сборки образа apt должен был обновить списки своих репозиториев, если только ему не помешала проблема вроде отсутствия подключения к интернету или некорректного DNS

**Comment by sxdxfan** [comment]
Закрыто по неактивности
